In [4]:
import pandas as pd

data = {
    "Name": ["Anjula", "Anjali", "Tharindu", "Savindi", "Kasun"],
    "Age": [25, 24, 29, 31, 27],
    "Study_Hours": [5, 6, 3, 8, 4],
    "Marks": [75, 82, 55, 92, 68]
}

df = pd.DataFrame(data)

df

       Name  Age  Study_Hours  Marks
0    Anjula   25            5     75
1    Anjali   24            6     82
2  Tharindu   29            3     55
3   Savindi   31            8     92
4     Kasun   27            4     68

In [5]:
df.shape

(5, 4)

In [6]:
df.columns

Index(['Name', 'Age', 'Study_Hours', 'Marks'], dtype='str')

In [7]:
df.dtypes

Name             str
Age            int64
Study_Hours    int64
Marks          int64
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      str
 1   Age          5 non-null      int64
 2   Study_Hours  5 non-null      int64
 3   Marks        5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 292.0 bytes

In [9]:
df.describe()

             Age  Study_Hours     Marks
count   5.000000     5.000000   5.00000
mean   27.200000     5.200000  74.40000
std     2.863564     1.923538  14.01071
min    24.000000     3.000000  55.00000
25%    25.000000     4.000000  68.00000
50%    27.000000     5.000000  75.00000
75%    29.000000     6.000000  82.00000
max    31.000000     8.000000  92.00000

In [10]:
df.isnull().sum()

Name           0
Age            0
Study_Hours    0
Marks          0
dtype: int64

In [11]:
messy_df = df.copy()

messy_df.loc[2, "Age"] = None
messy_df.loc[4, "Marks"] = None

messy_df

       Name   Age  Study_Hours  Marks
0    Anjula  25.0            5   75.0
1    Anjali  24.0            6   82.0
2  Tharindu   NaN            3   55.0
3   Savindi  31.0            8   92.0
4     Kasun  27.0            4    NaN

In [12]:
messy_df.isnull().sum()

Name           0
Age            1
Study_Hours    0
Marks          1
dtype: int64

In [13]:
messy_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      str
 1   Age          4 non-null      float64
 2   Study_Hours  5 non-null      int64
 3   Marks        4 non-null      float64
dtypes: float64(2), int64(1), str(1)
memory usage: 292.0 bytes

In [14]:
clean_df = messy_df.dropna()

clean_df

      Name   Age  Study_Hours  Marks
0   Anjula  25.0            5   75.0
1   Anjali  24.0            6   82.0
3  Savindi  31.0            8   92.0

In [15]:
messy_df.loc[2, "Age"] = 26

In [16]:
messy_df.isnull().sum()

Name           0
Age            0
Study_Hours    0
Marks          1
dtype: int64

In [17]:
messy_df.loc[4, "Marks"] = 78.5

In [18]:
messy_df.isnull().sum()

Name           0
Age            0
Study_Hours    0
Marks          0
dtype: int64

In [19]:
duplicate_df = pd.concat([df, df.iloc[[0]]], ignore_index=True)

duplicate_df

       Name  Age  Study_Hours  Marks
0    Anjula   25            5     75
1    Anjali   24            6     82
2  Tharindu   29            3     55
3   Savindi   31            8     92
4     Kasun   27            4     68
5    Anjula   25            5     75

In [20]:
duplicate_df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [21]:
clean_duplicate_df = duplicate_df.drop_duplicates()

In [22]:
clean_duplicate_df

       Name  Age  Study_Hours  Marks
0    Anjula   25            5     75
1    Anjali   24            6     82
2  Tharindu   29            3     55
3   Savindi   31            8     92
4     Kasun   27            4     68

In [23]:
clean_duplicate_df.shape

(5, 4)

In [28]:
df.sort_values(by="Marks")

       Name  Age  Study_Hours  Marks
2  Tharindu   29            3     55
4     Kasun   27            4     68
0    Anjula   25            5     75
1    Anjali   24            6     82
3   Savindi   31            8     92

In [ ]:
df.sort_values(by="Marks", ascending= False)

       Name  Age  Study_Hours  Marks
3   Savindi   31            8     92
1    Anjali   24            6     82
0    Anjula   25            5     75
4     Kasun   27            4     68
2  Tharindu   29            3     55

In [31]:
df["Marks"] >= 70

0     True
1     True
2    False
3     True
4    False
Name: Marks, dtype: bool

In [32]:
df[df["Marks"] >= 70]

      Name  Age  Study_Hours  Marks
0   Anjula   25            5     75
1   Anjali   24            6     82
3  Savindi   31            8     92

In [36]:
df[(df["Marks"] >= 70) & (df["Study_Hours"] >= 5)]

      Name  Age  Study_Hours  Marks
0   Anjula   25            5     75
1   Anjali   24            6     82
3  Savindi   31            8     92

In [37]:
df[(df["Marks"] >= 70) | (df["Study_Hours"] >= 5)]

      Name  Age  Study_Hours  Marks
0   Anjula   25            5     75
1   Anjali   24            6     82
3  Savindi   31            8     92

In [41]:
df.loc[df["Marks"] >= 70, ["Name", "Marks"]]

      Name  Marks
0   Anjula     75
1   Anjali     82
3  Savindi     92

In [45]:
df.loc[df["Marks"] >= 70, ["Name", "Marks"]].sort_values(by = "Marks", ascending = False)

      Name  Marks
3  Savindi     92
1   Anjali     82
0   Anjula     75

In [46]:
df[df["Name"].isin(["Anjula", "Kasun"])]

     Name  Age  Study_Hours  Marks
0  Anjula   25            5     75
4   Kasun   27            4     68