In [39]:
import pandas as pd
data = {
    "Name": ["Anjula", "Anjali", "Tharindu", "Savindi", "Kasun"],
    "Age": [25, 24, 29, 31, 27],
    "Study_Hours": [5, 6, 3, 8, 4],
    "Marks": [75, 82, 55, 92, 68]
}

df = pd.DataFrame(data)

df

       Name  Age  Study_Hours  Marks
0    Anjula   25            5     75
1    Anjali   24            6     82
2  Tharindu   29            3     55
3   Savindi   31            8     92
4     Kasun   27            4     68

In [40]:
X = df[["Study_Hours", "Age"]]
y = df["Marks"]

In [41]:
X

   Study_Hours  Age
0            5   25
1            6   24
2            3   29
3            8   31
4            4   27

In [42]:
y

0    75
1    82
2    55
3    92
4    68
Name: Marks, dtype: int64

In [43]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in /Users/anjula/INtREC/ML project/.venv/lib/python3.13/site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in /Users/anjula/INtREC/ML project/.venv/lib/python3.13/site-packages (from scikit-learn) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in /Users/anjula/INtREC/ML project/.venv/lib/python3.13/site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in /Users/anjula/INtREC/ML project/.venv/lib/python3.13/site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in /Users/anjula/INtREC/ML project/.venv/lib/python3.13/site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /Users/anjula/INtREC/ML project/.venv/lib/python3.13/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /Users/anjula/INtREC/ML project/.venv/lib/python3.13/site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [45]:
X_train

   Study_Hours  Age
4            4   27
2            3   29
0            5   25
3            8   31

In [46]:
X_test

   Study_Hours  Age
1            6   24

In [47]:
y_train

4    68
2    55
0    75
3    92
Name: Marks, dtype: int64

In [48]:
y_test

1    82
Name: Marks, dtype: int64

In [49]:
from sklearn.linear_model import LinearRegression

In [50]:
model = LinearRegression()

In [51]:
model.fit(X_train,y_train)

LinearRegression()

In [52]:
model.coef_

array([ 7.66666667, -1.16666667])

In [53]:
model.intercept_

np.float64(66.83333333333334)

In [54]:
y_pred = model.predict(X_test)

In [55]:
y_pred

array([84.83333333])

In [56]:
from sklearn.metrics import mean_absolute_error

In [57]:
mae = mean_absolute_error(y_test, y_pred)
mae

2.8333333333333286

In [58]:
data = {
    "Name": ["Anjula", "Anjali", "Tharindu", "Savindi", "Kasun",
             "Nimal", "Kavindu", "Dilshan", "Sahan", "Amaya",
             "Hasini", "Ravindu", "Chamodi", "Pasindu", "Thilini",
             "Dinesh", "Nethmi", "Isuru", "Sachini", "Malith"],

    "Age": [25, 24, 29, 31, 27, 22, 26, 28, 23, 30,
            21, 25, 27, 24, 29, 32, 23, 26, 28, 22],

    "Study_Hours": [5, 6, 3, 8, 4, 7, 5, 2, 6, 4,
                    8, 5, 7, 3, 6, 4, 9, 5, 7, 3],

    "Marks": [75, 82, 55, 92, 68, 85, 72, 50, 80, 65,
              95, 74, 88, 58, 79, 63, 96, 76, 89, 54]
}

df = pd.DataFrame(data)

In [59]:
df.shape

(20, 4)

In [60]:
X = df[["Study_Hours", "Age"]]
y = df["Marks"]

In [61]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [62]:
X_test

    Study_Hours  Age
0             5   25
17            5   26
15            4   32
1             6   24

In [63]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [64]:
y_pred = model.predict(X_test)
y_pred

array([71.76162218, 71.86442174, 65.29949738, 78.84054431])

In [65]:
y_test

0     75
17    76
15    63
1     82
Name: Marks, dtype: int64

In [66]:
mae = mean_absolute_error(y_test, y_pred)
mae

3.208227289585757

In [67]:
print("Actual:", y_test.values)
print("Predicted:", y_pred)

Actual: [75 76 63 82]
Predicted: [71.76162218 71.86442174 65.29949738 78.84054431]

In [68]:
from sklearn.metrics import r2_score

In [69]:
r2 = r2_score(y_test, y_pred)
r2

0.774421331796348

In [70]:
model.coef_

array([7.18172168, 0.10279955])

In [71]:
model.intercept_

np.float64(33.283024900564)

In [72]:
66.8333 + (7.6667 * 5) + (-1.1667 * 25)

75.99929999999999

In [73]:
model.coef_, model.intercept_

(array([7.18172168, 0.10279955]), np.float64(33.283024900564))

In [74]:
import numpy as np

X = np.array([
    [1, 2, 20],
    [1, 4, 20],
    [1, 6, 30]
])

y = np.array([50, 70, 90])

beta = np.linalg.inv(X.T @ X) @ X.T @ y

beta

array([3.00000000e+01, 1.00000000e+01, 1.95399252e-14])

In [75]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X[:, 1:], y)

print("Sklearn coefficients:", model.coef_)
print("Sklearn intercept:", model.intercept_)

Sklearn coefficients: [1.00000000e+01 1.00485917e-15]
Sklearn intercept: 29.999999999999993

In [76]:
from sklearn.metrics import mean_absolute_error

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

train_mae = mean_absolute_error(y_train, y_train_pred)
test_mae = mean_absolute_error(y_test, y_test_pred)

print("Training MAE:", train_mae)
print("Test MAE:", test_mae)

Training MAE: 9.375
Test MAE: 6.0000000000000036

/Users/anjula/INtREC/ML project/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2820: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
/Users/anjula/INtREC/ML project/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2820: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

In [79]:
from sklearn.preprocessing import PolynomialFeatures
X = df[["Study_Hours", "Age"]]

poly = PolynomialFeatures(degree=2)

X_poly = poly.fit_transform(X)

print("Original shape:", X.shape)
print("Polynomial shape:", X_poly.shape)
print("Feature names:", poly.get_feature_names_out(X.columns))

Original shape: (20, 2)
Polynomial shape: (20, 6)
Feature names: ['1' 'Study_Hours' 'Age' 'Study_Hours^2' 'Study_Hours Age' 'Age^2']

In [83]:
X_poly_train, X_poly_test, y_poly_train, y_poly_test = train_test_split(
    X_poly, y, test_size=0.2, random_state=42
)

poly_model = LinearRegression()
poly_model.fit(X_poly_train, y_poly_train)

y_poly_train_pred = poly_model.predict(X_poly_train)
y_poly_test_pred = poly_model.predict(X_poly_test)

poly_train_mae = mean_absolute_error(y_poly_train, y_poly_train_pred)
poly_test_mae = mean_absolute_error(y_poly_test, y_poly_test_pred)

print("Polynomial Training MAE:", poly_train_mae)
print("Polynomial Test MAE:", poly_test_mae)

Polynomial Training MAE: 1.3982841006045232
Polynomial Test MAE: 1.6250224094352603

In [84]:
poly10 = PolynomialFeatures(degree=10)

X_poly10 = poly10.fit_transform(X)

X_train10, X_test10, y_train10, y_test10 = train_test_split(
    X_poly10, y, test_size=0.2, random_state=42
)

model10 = LinearRegression()
model10.fit(X_train10, y_train10)

y_train10_pred = model10.predict(X_train10)
y_test10_pred = model10.predict(X_test10)

train_mae10 = mean_absolute_error(y_train10, y_train10_pred)
test_mae10 = mean_absolute_error(y_test10, y_test10_pred)

print("Degree 10 Training MAE:", train_mae10)
print("Degree 10 Test MAE:", test_mae10)

Degree 10 Training MAE: 3.364775329687223
Degree 10 Test MAE: 9.499154914168784

In [85]:
from sklearn.model_selection import cross_val_score

for degree in range(1, 11):
    poly = PolynomialFeatures(degree=degree)
    X_poly_degree = poly.fit_transform(X)

    model = LinearRegression()

    scores = cross_val_score(
        model,
        X_poly_degree,
        y,
        cv=5,
        scoring="neg_mean_absolute_error"
    )

    mean_mae = -scores.mean()

    print(f"Degree {degree}: CV MAE = {mean_mae:.3f}")

Degree 1: CV MAE = 2.206
Degree 2: CV MAE = 2.342
Degree 3: CV MAE = 2.961
Degree 4: CV MAE = 4.172
Degree 5: CV MAE = 4.604
Degree 6: CV MAE = 5.558
Degree 7: CV MAE = 9.053
Degree 8: CV MAE = 8.731
Degree 9: CV MAE = 10.117
Degree 10: CV MAE = 13.946

In [86]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("poly", PolynomialFeatures()),
    ("model", LinearRegression())
])

param_grid = {
    "poly__degree": range(1, 11)
}

grid_search = GridSearchCV(
    pipeline,
    param_grid,
    cv=5,
    scoring="neg_mean_absolute_error"
)

grid_search.fit(X, y)

print("Best Degree:", grid_search.best_params_["poly__degree"])
print("Best CV MAE:", -grid_search.best_score_)

Best Degree: 1
Best CV MAE: 2.206181555533806

In [87]:
best_model = grid_search.best_estimator_

y_test_pred = best_model.predict(X_test)

final_test_mae = mean_absolute_error(y_test, y_test_pred)

print("Best Degree:", grid_search.best_params_["poly__degree"])
print("CV MAE:", -grid_search.best_score_)
print("Final Test MAE:", final_test_mae)

Best Degree: 1
CV MAE: 2.206181555533806
Final Test MAE: 2.709241390783564

In [88]:
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

z_values = np.array([-3, 0, 2, 5])

probabilities = sigmoid(z_values)

print(probabilities)

[0.04742587 0.5        0.88079708 0.99330715]

In [91]:
from sklearn.linear_model import LogisticRegression

X_class = df[["Study_Hours"]]

y_class = (df["Marks"] >= 70).astype(int)

print("X:")
print(X_class.head())

print("\ny:")
print(y_class.head())

X:
   Study_Hours
0            5
1            6
2            3
3            8
4            4

y:
0    1
1    1
2    0
3    1
4    0
Name: Marks, dtype: int64

In [92]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(
    X_class,
    y_class,
    test_size=0.2,
    random_state=42
)

log_model = LogisticRegression()

log_model.fit(X_train, y_train)

print("Coefficient:", log_model.coef_)
print("Intercept:", log_model.intercept_)

Coefficient: [[1.54630566]]
Intercept: [-6.98702614]

In [93]:
probabilities = log_model.predict_proba(X_test)

print(probabilities)

[[0.32202043 0.67797957]
 [0.32202043 0.67797957]
 [0.69036013 0.30963987]
 [0.09188712 0.90811288]]

In [94]:
y_pred = log_model.predict(X_test)

print("Predicted classes:")
print(y_pred)

print("\nActual classes:")
print(y_test.to_numpy())

Predicted classes:
[1 1 0 1]

Actual classes:
[1 1 0 1]

In [95]:
from sklearn.metrics import accuracy_score, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(cm)

Accuracy: 1.0

Confusion Matrix:
[[1 0]
 [0 3]]

In [96]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 1.0
Recall: 1.0
F1-score: 1.0

In [97]:
print("Coefficient:", log_model.coef_[0][0])
print("Intercept:", log_model.intercept_[0])

boundary = -log_model.intercept_[0] / log_model.coef_[0][0]

print("Decision Boundary:", boundary)

Coefficient: 1.546305663292117
Intercept: -6.987026137726854
Decision Boundary: 4.518528453715502

In [98]:
probabilities = log_model.predict_proba(X_test)[:, 1]

threshold = 0.7

y_pred_07 = (probabilities >= threshold).astype(int)

print("Probabilities:", probabilities)
print("Predictions:", y_pred_07)
print("Actual:", y_test.to_numpy())

Probabilities: [0.67797957 0.67797957 0.30963987 0.90811288]
Predictions: [0 0 0 1]
Actual: [1 1 0 1]

In [99]:
precision_07 = precision_score(y_test, y_pred_07)
recall_07 = recall_score(y_test, y_pred_07)
f1_07 = f1_score(y_test, y_pred_07)

print("Precision:", precision_07)
print("Recall:", recall_07)
print("F1:", f1_07)

Precision: 1.0
Recall: 0.3333333333333333
F1: 0.5

In [100]:
from sklearn.metrics import roc_auc_score, roc_curve

y_prob = log_model.predict_proba(X_test)[:, 1]

auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC:", auc)

ROC-AUC: 1.0

In [101]:
gini_left = 1 - (1/7)**2 - (6/7)**2
gini_right = 1 - (11/12)**2 - (1/12)**2

weighted_gini = (7/19) * gini_left + (12/19) * gini_right

print("Left Gini:", gini_left)
print("Right Gini:", gini_right)
print("Weighted Gini:", weighted_gini)

Left Gini: 0.24489795918367352
Right Gini: 0.15277777777777787
Weighted Gini: 0.18671679197994995

In [102]:
from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier(
    criterion="gini",
    random_state=42
)

tree_model.fit(X_train, y_train)

print("Tree trained successfully")

Tree trained successfully

In [103]:
from sklearn.tree import export_text

tree_rules = export_text(
    tree_model,
    feature_names=["Study_Hours"]
)

print(tree_rules)

|--- Study_Hours <= 4.50
|   |--- class: 0
|--- Study_Hours >  4.50
|   |--- class: 1

In [104]:
y_tree_pred = tree_model.predict(X_test)

print("Predicted:", y_tree_pred)
print("Actual:   ", y_test.to_numpy())

Predicted: [1 1 0 1]
Actual:    [1 1 0 1]

In [105]:
for depth in [1, 2, 3, 5, 10]:
    tree = DecisionTreeClassifier(
        criterion="gini",
        max_depth=depth,
        random_state=42
    )

    tree.fit(X_train, y_train)

    train_acc = tree.score(X_train, y_train)
    test_acc = tree.score(X_test, y_test)

    print(
        f"Depth {depth}: "
        f"Train Accuracy = {train_acc:.2f}, "
        f"Test Accuracy = {test_acc:.2f}"
    )

Depth 1: Train Accuracy = 1.00, Test Accuracy = 1.00
Depth 2: Train Accuracy = 1.00, Test Accuracy = 1.00
Depth 3: Train Accuracy = 1.00, Test Accuracy = 1.00
Depth 5: Train Accuracy = 1.00, Test Accuracy = 1.00
Depth 10: Train Accuracy = 1.00, Test Accuracy = 1.00

In [106]:
from sklearn.ensemble import RandomForestClassifier

forest_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

forest_model.fit(X_train, y_train)

print("Random Forest trained successfully")

Random Forest trained successfully

In [107]:
y_forest_pred = forest_model.predict(X_test)

print("Predicted:", y_forest_pred)
print("Actual:   ", y_test.to_numpy())

forest_accuracy = accuracy_score(y_test, y_forest_pred)

print("Random Forest Accuracy:", forest_accuracy)

Predicted: [1 1 0 1]
Actual:    [1 1 0 1]
Random Forest Accuracy: 1.0

In [108]:
for n in [1, 5, 10, 50, 100]:
    forest = RandomForestClassifier(
        n_estimators=n,
        random_state=42
    )

    forest.fit(X_train, y_train)

    accuracy = forest.score(X_test, y_test)

    print(f"Trees {n}: Test Accuracy = {accuracy:.2f}")

Trees 1: Test Accuracy = 1.00
Trees 5: Test Accuracy = 1.00
Trees 10: Test Accuracy = 1.00
Trees 50: Test Accuracy = 1.00
Trees 100: Test Accuracy = 1.00

In [109]:
for i, tree in enumerate(forest_model.estimators_[:5]):
    print(f"Tree {i + 1}:")
    print(export_text(tree, feature_names=["Study_Hours"]))
    print()

Tree 1:
|--- Study_Hours <= 4.50
|   |--- class: 0.0
|--- Study_Hours >  4.50
|   |--- class: 1.0


Tree 2:
|--- Study_Hours <= 4.50
|   |--- class: 0.0
|--- Study_Hours >  4.50
|   |--- class: 1.0


Tree 3:
|--- Study_Hours <= 4.50
|   |--- class: 0.0
|--- Study_Hours >  4.50
|   |--- class: 1.0


Tree 4:
|--- Study_Hours <= 4.50
|   |--- class: 0.0
|--- Study_Hours >  4.50
|   |--- class: 1.0


Tree 5:
|--- Study_Hours <= 4.50
|   |--- class: 0.0
|--- Study_Hours >  4.50
|   |--- class: 1.0

In [110]:
importance = forest_model.feature_importances_

for feature, score in zip(X_class.columns, importance):
    print(f"{feature}: {score:.3f}")

Study_Hours: 1.000

In [111]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train, y_train)

print("KNN trained successfully")

KNN trained successfully

In [112]:
y_knn_pred = knn_model.predict(X_test)

print("Predicted:", y_knn_pred)
print("Actual:   ", y_test.to_numpy())

knn_accuracy = accuracy_score(y_test, y_knn_pred)

print("KNN Accuracy:", knn_accuracy)

Predicted: [1 1 0 1]
Actual:    [1 1 0 1]
KNN Accuracy: 1.0

In [113]:
for k in [1, 3, 5, 7, 9]:
    knn = KNeighborsClassifier(n_neighbors=k)

    knn.fit(X_train, y_train)

    train_acc = knn.score(X_train, y_train)
    test_acc = knn.score(X_test, y_test)

    print(
        f"K={k}: "
        f"Train Accuracy={train_acc:.2f}, "
        f"Test Accuracy={test_acc:.2f}"
    )

K=1: Train Accuracy=1.00, Test Accuracy=1.00
K=3: Train Accuracy=1.00, Test Accuracy=1.00
K=5: Train Accuracy=1.00, Test Accuracy=1.00
K=7: Train Accuracy=1.00, Test Accuracy=1.00
K=9: Train Accuracy=1.00, Test Accuracy=1.00

In [114]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X_class)

print("Original:")
print(X_class.head())

print("\nScaled:")
print(X_scaled[:5])

Original:
   Study_Hours
0            5
1            6
2            3
3            8
4            4

Scaled:
[[-0.1863522 ]
 [ 0.34608266]
 [-1.25122194]
 [ 1.4109524 ]
 [-0.71878707]]

In [115]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

knn_scaled = KNeighborsClassifier(n_neighbors=5)

knn_scaled.fit(X_train_scaled, y_train)

y_knn_scaled_pred = knn_scaled.predict(X_test_scaled)

print("Predicted:", y_knn_scaled_pred)
print("Actual:   ", y_test.to_numpy())
print("Accuracy:", accuracy_score(y_test, y_knn_scaled_pred))

Predicted: [1 1 0 1]
Actual:    [1 1 0 1]
Accuracy: 1.0

In [116]:
from sklearn.pipeline import Pipeline

knn_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(n_neighbors=5))
])

knn_pipeline.fit(X_train, y_train)

y_pred = knn_pipeline.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0

In [117]:
from sklearn.svm import SVC

svm_model = SVC(kernel="linear")

svm_model.fit(X_train, y_train)

y_svm_pred = svm_model.predict(X_test)

print("Predicted:", y_svm_pred)
print("Actual:   ", y_test.to_numpy())
print("Accuracy:", accuracy_score(y_test, y_svm_pred))

Predicted: [1 1 0 1]
Actual:    [1 1 0 1]
Accuracy: 1.0

In [118]:
for c in [0.01, 0.1, 1, 10, 100]:
    svm = SVC(
        kernel="linear",
        C=c
    )

    svm.fit(X_train, y_train)

    train_acc = svm.score(X_train, y_train)
    test_acc = svm.score(X_test, y_test)

    print(
        f"C={c}: "
        f"Train Accuracy={train_acc:.2f}, "
        f"Test Accuracy={test_acc:.2f}"
    )

C=0.01: Train Accuracy=0.62, Test Accuracy=0.75
C=0.1: Train Accuracy=1.00, Test Accuracy=1.00
C=1: Train Accuracy=1.00, Test Accuracy=1.00
C=10: Train Accuracy=1.00, Test Accuracy=1.00
C=100: Train Accuracy=1.00, Test Accuracy=1.00

In [119]:
for kernel in ["linear", "rbf", "poly"]:
    svm = SVC(
        kernel=kernel,
        C=1
    )

    svm.fit(X_train, y_train)

    accuracy = svm.score(X_test, y_test)

    print(f"Kernel={kernel}: Test Accuracy={accuracy:.2f}")

Kernel=linear: Test Accuracy=1.00
Kernel=rbf: Test Accuracy=1.00
Kernel=poly: Test Accuracy=1.00

In [120]:
from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()

nb_model.fit(X_train, y_train)

y_nb_pred = nb_model.predict(X_test)

print("Predicted:", y_nb_pred)
print("Actual:   ", y_test.to_numpy())
print("Accuracy:", accuracy_score(y_test, y_nb_pred))

Predicted: [1 1 0 1]
Actual:    [1 1 0 1]
Accuracy: 1.0

In [121]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "SVM": SVC(kernel="linear"),
    "Naive Bayes": GaussianNB()
}

for name, model in models.items():
    model.fit(X_train, y_train)
    accuracy = model.score(X_test, y_test)

    print(f"{name}: {accuracy:.2f}")

Logistic Regression: 1.00
Decision Tree: 1.00
Random Forest: 1.00
KNN: 1.00
SVM: 1.00
Naive Bayes: 1.00

In [122]:
from sklearn.model_selection import cross_val_score

for name, model in models.items():

    scores = cross_val_score(
        model,
        X_class,
        y_class,
        cv=5,
        scoring="accuracy"
    )

    print(
        f"{name}: "
        f"Mean CV Accuracy = {scores.mean():.3f}"
    )

Logistic Regression: Mean CV Accuracy = 1.000
Decision Tree: Mean CV Accuracy = 1.000
Random Forest: Mean CV Accuracy = 1.000
KNN: Mean CV Accuracy = 1.000
SVM: Mean CV Accuracy = 1.000
Naive Bayes: Mean CV Accuracy = 1.000