In [1]:
Hello World

SyntaxError: invalid syntax (961555472.py, line 1)

In [2]:
print ("Hello world")

Hello world

In [3]:
name = "Anjula"
age = 25

print (name)
print(age)

Anjula
25

In [4]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)
print(numbers.mean())

ModuleNotFoundError: No module named 'numpy'

In [4]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)
print(numbers.mean())

ModuleNotFoundError: No module named 'numpy'

In [5]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)
print(numbers.mean())

[10 20 30 40 50]
30.0

In [6]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)
print("Mean is : " ,numbers.mean())

[10 20 30 40 50]
Mean is :  30.0

In [7]:
import pandas as pd

In [8]:
data = {

_IncompleteInputError: incomplete input (3185009576.py, line 1)

In [9]:
data = {
    "Name" ["Anjula","Anjali","Tharindu","Savindi"],
    "Age" [25,25,29,31],
    "Marks" [70,80,90,100]
}

<>:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:3: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:4: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
/var/folders/rd/nk8dl3y111d2tg7vjm9phvmw0000gn/T/ipykernel_69627/3857932786.py:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  "Name" ["Anjula","Anjali","Tharindu","Savindi"],
/var/folders/rd/nk8dl3y111d2tg7vjm9phvmw0000gn/T/ipykernel_69627/3857932786.py:3: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  "Age" [25,25,29,31],
/var/folders/rd/nk8dl3y111d2tg7vjm9phvmw0000gn/T/ipykernel_69627/3857932786.py:4: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  "Marks" [70,80,90,100]

TypeError: string indices must be integers, not 'tuple'

In [10]:
data = {
    "Name" ["Anjula","Anjali","Tharindu","Savindi"],
    "Age" [25,25,29,31],
    "Marks" [70,80,90,100]
}
df = pd.DataFrame(data)
print(df)

TypeError: string indices must be integers, not 'tuple'

In [11]:
import pandas as pd
data = {
    "Name" ["Anjula","Anjali","Tharindu","Savindi"],
    "Age" [25,25,29,31],
    "Marks" [70,80,90,100]
}
df = pd.DataFrame(data)
print(df)

<>:5: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
/var/folders/rd/nk8dl3y111d2tg7vjm9phvmw0000gn/T/ipykernel_69627/731765383.py:5: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  "Marks" [70,80,90,100]

TypeError: string indices must be integers, not 'tuple'

In [3]:
import pandas as pd

data = {
    "Name" : ["Anjula","Anjali","Tharindu","Savindi"],
    "Age" : [25,25,29,31],
    "Marks" : [70,80,90,100]
}
df = pd.DataFrame(data)
print(df)

       Name  Age  Marks
0    Anjula   25     70
1    Anjali   25     80
2  Tharindu   29     90
3   Savindi   31    100

In [4]:
df["Marks"]

0     70
1     80
2     90
3    100
Name: Marks, dtype: int64

In [5]:
df["Age"]

0    25
1    25
2    29
3    31
Name: Age, dtype: int64

In [6]:
df["marks"]

KeyError: 'marks'

In [7]:
df["Marks"]

0     70
1     80
2     90
3    100
Name: Marks, dtype: int64

In [8]:
df[df["Marks"]>80]

       Name  Age  Marks
2  Tharindu   29     90
3   Savindi   31    100

In [9]:
df["Marks"].mean()

np.float64(85.0)

In [10]:
df.describe

<bound method NDFrame.describe of        Name  Age  Marks
0    Anjula   25     70
1    Anjali   25     80
2  Tharindu   29     90
3   Savindi   31    100>

In [11]:
df.describe()

        Age       Marks
count   4.0    4.000000
mean   27.5   85.000000
std     3.0   12.909944
min    25.0   70.000000
25%    25.0   77.500000
50%    27.0   85.000000
75%    29.5   92.500000
max    31.0  100.000000

In [12]:
df.isnull().sum()

Name     0
Age      0
Marks    0
dtype: int64