In [2]:
print ("Hello world")

Hello world

In [3]:
name = "Anjula"
age = 25

print (name)
print(age)

Anjula
25

In [5]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)
print(numbers.mean())

[10 20 30 40 50]
30.0

In [6]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)
print("Mean is : " ,numbers.mean())

[10 20 30 40 50]
Mean is :  30.0

In [7]:
import pandas as pd

In [3]:
import pandas as pd

data = {
    "Name" : ["Anjula","Anjali","Tharindu","Savindi"],
    "Age" : [25,25,29,31],
    "Marks" : [70,80,90,100]
}
df = pd.DataFrame(data)
print(df)

       Name  Age  Marks
0    Anjula   25     70
1    Anjali   25     80
2  Tharindu   29     90
3   Savindi   31    100

In [4]:
df["Marks"]

0     70
1     80
2     90
3    100
Name: Marks, dtype: int64

In [5]:
df["Age"]

0    25
1    25
2    29
3    31
Name: Age, dtype: int64

In [7]:
df["Marks"]

0     70
1     80
2     90
3    100
Name: Marks, dtype: int64

In [8]:
df[df["Marks"]>80]

       Name  Age  Marks
2  Tharindu   29     90
3   Savindi   31    100

In [9]:
df["Marks"].mean()

np.float64(85.0)

In [10]:
df.describe

<bound method NDFrame.describe of        Name  Age  Marks
0    Anjula   25     70
1    Anjali   25     80
2  Tharindu   29     90
3   Savindi   31    100>

In [11]:
df.describe()

        Age       Marks
count   4.0    4.000000
mean   27.5   85.000000
std     3.0   12.909944
min    25.0   70.000000
25%    25.0   77.500000
50%    27.0   85.000000
75%    29.5   92.500000
max    31.0  100.000000

In [12]:
df.isnull().sum()

Name     0
Age      0
Marks    0
dtype: int64

In [14]:
df["Age"].max()

np.int64(31)